export const GMASTER_ABI = [
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "name", type: "string" },
      { name: "char_class", type: "string" },
    ],
    name: "create_character",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "adventure_id", type: "string" }],
    name: "start_adventure",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "game_id", type: "uint256" },
      { name: "action", type: "string" },
    ],
    name: "take_action",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "item_id", type: "uint256" },
      { name: "game_id", type: "uint256" },
    ],
    name: "use_item",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "address", type: "address" }],
    name: "get_character",
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "owner", type: "address" },
          { name: "name", type: "string" },
          { name: "char_class", type: "string" },
          { name: "level", type: "uint256" },
          { name: "exp", type: "uint256" },
          { name: "hp", type: "uint256" },
          { name: "max_hp", type: "uint256" },
          { name: "stat_str", type: "uint256" },
          { name: "stat_dex", type: "uint256" },
          { name: "stat_int", type: "uint256" },
          { name: "stat_wis", type: "uint256" },
          { name: "is_alive", type: "bool" },
          { name: "victories", type: "uint256" },
          { name: "created_at", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "game_id", type: "uint256" }],
    name: "get_game",
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "player", type: "address" },
          { name: "adventure_id", type: "string" },
          { name: "current_room", type: "uint256" },
          { name: "total_rooms", type: "uint256" },
          { name: "turn_count", type: "uint256" },
          { name: "is_active", type: "bool" },
          { name: "is_victory", type: "bool" },
          { name: "started_at", type: "uint256" },
          { name: "last_action_at", type: "uint256" },
          { name: "state_json", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "player", type: "address" }],
    name: "get_active_game_for_player",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "game_id", type: "uint256" }],
    name: "get_event_log",
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "player", type: "address" }],
    name: "get_player_items",
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "name", type: "string" },
          { name: "owner", type: "address" },
          { name: "item_type", type: "string" },
          { name: "description", type: "string" },
          { name: "power", type: "uint256" },
          { name: "is_consumed", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_leaderboard_stats",
    outputs: [{ name: "total_victories", type: "uint256" }, { name: "total_deaths", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_adventures",
    outputs: [{ name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_all_games",
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "id", type: "uint256" },
          { name: "player", type: "address" },
          { name: "adventure_id", type: "string" },
          { name: "current_room", type: "uint256" },
          { name: "total_rooms", type: "uint256" },
          { name: "turn_count", type: "uint256" },
          { name: "is_active", type: "bool" },
          { name: "is_victory", type: "bool" },
          { name: "started_at", type: "uint256" },
          { name: "last_action_at", type: "uint256" },
          { name: "state_json", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
